language: ruby
rvm:
  - 2.2.4
cache: bundler
sudo: required
env:
  matrix:
  - DB=mysql
services:
  - redis
  - mysql
gemfile:
 - Gemfile
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - gem install capistrano --no-ri --no-rdoc
  - cd anemometer
before_script:
  - RAILS_ENV=test bundle install --system
  - gem list
  - gem uninstall sqlite3
  - mysql -e 'create database IF NOT EXISTS weather_machine_test;'
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - cat ~/.ssh/id_rsa.pub
script:
  - bundle exec cap production deploy
branches:
  only:
  - master
