language: ruby

rvm:
  - 2.2.4
  - 2.2.3
  - jruby
  - rbx-2

cache: bundler

env:
  - DB=mysql

services:
  - redis
  - mysql

gemfile:
  - Gemfile

before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - gem install capistrano --no-ri --no-rdoc
  - gem uninstall sqlite3
  - cd anemometer

before_script:
  - bundle install
  - mysql -e 'create database IF NOT EXISTS weather_machine;'
  - RAILS_ENV=test bundle exec rake db:migrate --trace

script:
  - cap production deploy

branches:
  only:
    - master